"""Lightweight ID->name tables for Pokémon GSC.

This module intentionally uses simple Python data structures and safe fallbacks.
The goal is a better UX in the GUI (display readable names; allow dropdowns).

Notes:
- Species list is provided for National Dex IDs 1..251 (Gen 2).
- Move/item tables are partial; unknown IDs fall back to "Move {id}" / "Item {id}".
"""

from __future__ import annotations

from typing import Dict, List


# Index = species id. Index 0 is unused.
SPECIES_NAMES: List[str] = [
    "",
    "Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard",
    "Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree",
    "Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate",
    "Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew","Sandslash",
    "Nidoran♀","Nidorina","Nidoqueen","Nidoran♂","Nidorino","Nidoking","Clefairy","Clefable",
    "Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume",
    "Paras","Parasect","Venonat","Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck",
    "Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam",
    "Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel",
    "Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton",
    "Farfetch'd","Doduo","Dodrio","Seel","Dewgong","Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar",
    "Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Cubone","Marowak",
    "Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan",
    "Horsea","Seadra","Goldeen","Seaking","Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar",
    "Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon",
    "Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres",
    "Dratini","Dragonair","Dragonite","Mewtwo","Mew",
    "Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion",
    "Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian",
    "Spinarak","Ariados","Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic",
    "Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed",
    "Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon",
    "Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce",
    "Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa","Ursaring",
    "Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory",
    "Houndour","Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop",
    "Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar",
    "Lugia","Ho-Oh","Celebi",
]


# Partial move name table; unknowns fall back to "Move {id}".
# IDs follow the internal move IDs used by GSC.
MOVE_NAMES: Dict[int, str] = {
    1: "Pound",
    2: "Karate Chop",
    3: "DoubleSlap",
    4: "Comet Punch",
    5: "Mega Punch",
    6: "Pay Day",
    7: "Fire Punch",
    8: "Ice Punch",
    9: "ThunderPunch",
    10: "Scratch",
    15: "Cut",
    16: "Gust",
    17: "Wing Attack",
    18: "Whirlwind",
    19: "Fly",
    20: "Bind",
    21: "Slam",
    22: "Vine Whip",
    23: "Stomp",
    24: "Double Kick",
    25: "Mega Kick",
    26: "Jump Kick",
    27: "Rolling Kick",
    28: "Sand-Attack",
    29: "Headbutt",
    33: "Tackle",
    34: "Body Slam",
    35: "Wrap",
    36: "Take Down",
    37: "Thrash",
    38: "Double-Edge",
    39: "Tail Whip",
    40: "Poison Sting",
    41: "Twineedle",
    42: "Pin Missile",
    43: "Leer",
    44: "Bite",
    45: "Growl",
    46: "Roar",
    52: "Ember",
    53: "Flamethrower",
    54: "Mist",
    55: "Water Gun",
    56: "Hydro Pump",
    57: "Surf",
    58: "Ice Beam",
    59: "Blizzard",
    60: "Psybeam",
    61: "BubbleBeam",
    62: "Aurora Beam",
    63: "Hyper Beam",
    64: "Peck",
    65: "Drill Peck",
    66: "Submission",
    67: "Low Kick",
    68: "Counter",
    69: "Seismic Toss",
    70: "Strength",
    71: "Absorb",
    72: "Mega Drain",
    73: "Leech Seed",
    74: "Growth",
    75: "Razor Leaf",
    76: "SolarBeam",
    77: "PoisonPowder",
    78: "Stun Spore",
    79: "Sleep Powder",
    80: "Petal Dance",
    81: "String Shot",
    82: "Dragon Rage",
    83: "Fire Spin",
    84: "ThunderShock",
    85: "Thunderbolt",
    86: "Thunder Wave",
    87: "Thunder",
    88: "Rock Throw",
    89: "Earthquake",
    90: "Fissure",
    91: "Dig",
    92: "Toxic",
    93: "Confusion",
    94: "Psychic",
    95: "Hypnosis",
    96: "Meditate",
    97: "Agility",
    98: "Quick Attack",
    99: "Rage",
    100: "Teleport",
    101: "Night Shade",
    102: "Mimic",
    103: "Screech",
    104: "Double Team",
    105: "Recover",
    106: "Harden",
    107: "Minimize",
    108: "Smokescreen",
    109: "Confuse Ray",
    110: "Withdraw",
    111: "Defense Curl",
    112: "Barrier",
    113: "Light Screen",
    114: "Haze",
    115: "Reflect",
    116: "Focus Energy",
    117: "Bide",
    118: "Metronome",
    119: "Mirror Move",
    120: "Selfdestruct",
    121: "Egg Bomb",
    122: "Lick",
    123: "Smog",
    124: "Sludge",
    125: "Bone Club",
    126: "Fire Blast",
    127: "Waterfall",
    128: "Clamp",
    129: "Swift",
    130: "Skull Bash",
    131: "Spike Cannon",
    132: "Constrict",
    133: "Amnesia",
    134: "Kinesis",
    135: "Softboiled",
    136: "High Jump Kick",
    137: "Glare",
    138: "Dream Eater",
    139: "Poison Gas",
    140: "Barrage",
    141: "Leech Life",
    142: "Lovely Kiss",
    143: "Sky Attack",
    144: "Transform",
    145: "Bubble",
    146: "Dizzy Punch",
    147: "Spore",
    148: "Flash",
    149: "Psywave",
    150: "Splash",
    151: "Acid Armor",
    152: "Crabhammer",
    153: "Explosion",
    154: "Fury Swipes",
    155: "Bonemerang",
    156: "Rest",
    157: "Rock Slide",
    158: "Hyper Fang",
    159: "Sharpen",
    160: "Conversion",
    161: "Tri Attack",
    162: "Super Fang",
    163: "Slash",
    164: "Substitute",
    165: "Struggle",
    # Gen 2 additions (partial)
    166: "Sketch",
    167: "Triple Kick",
    168: "Thief",
    169: "Spider Web",
    170: "Mind Reader",
    171: "Nightmare",
    172: "Flame Wheel",
    173: "Snore",
    174: "Curse",
    175: "Flail",
    176: "Conversion2",
    177: "Aeroblast",
    178: "Cotton Spore",
    179: "Reversal",
    180: "Spite",
    181: "Powder Snow",
    182: "Protect",
    183: "Mach Punch",
    184: "Scary Face",
    185: "Feint Attack",
    186: "Sweet Kiss",
    187: "Belly Drum",
    188: "Sludge Bomb",
    189: "Mud-Slap",
    190: "Octazooka",
    191: "Spikes",
    192: "Zap Cannon",
    193: "Foresight",
    194: "Destiny Bond",
    195: "Perish Song",
    196: "Icy Wind",
    197: "Detect",
    198: "Bone Rush",
    199: "Lock-On",
    200: "Outrage",
    201: "Sandstorm",
    202: "Giga Drain",
    203: "Endure",
    204: "Charm",
    205: "Rollout",
    206: "False Swipe",
    207: "Swagger",
    208: "Milk Drink",
    209: "Spark",
    210: "Fury Cutter",
    211: "Steel Wing",
    212: "Mean Look",
    213: "Attract",
    214: "Sleep Talk",
    215: "Heal Bell",
    216: "Return",
    217: "Present",
    218: "Frustration",
    219: "Safeguard",
    220: "Pain Split",
    221: "Sacred Fire",
    222: "Magnitude",
    223: "DynamicPunch",
    224: "Megahorn",
    225: "DragonBreath",
    226: "Baton Pass",
    227: "Encore",
    228: "Pursuit",
    229: "Rapid Spin",
    230: "Sweet Scent",
    231: "Iron Tail",
    232: "Metal Claw",
    233: "Vital Throw",
    234: "Morning Sun",
    235: "Synthesis",
    236: "Moonlight",
    237: "Hidden Power",
    238: "Cross Chop",
    239: "Twister",
    240: "Rain Dance",
    241: "Sunny Day",
    242: "Crunch",
    243: "Mirror Coat",
    244: "Psych Up",
    245: "ExtremeSpeed",
    246: "AncientPower",
    247: "Shadow Ball",
    248: "Future Sight",
    249: "Rock Smash",
    250: "Whirlpool",
    251: "Beat Up",
}


# Partial item name table (held items, bag items). Unknowns fall back to "Item {id}".
ITEM_NAMES: Dict[int, str] = {
    0x00: "(None)",
    0x01: "Master Ball",
    0x02: "Ultra Ball",
    0x03: "Great Ball",
    0x04: "Poké Ball",
    0x0F: "Potion",
    0x10: "Super Potion",
    0x11: "Hyper Potion",
    0x12: "Max Potion",
    0x13: "Full Restore",
    0x14: "Revive",
    0x15: "Max Revive",
    0x1D: "Escape Rope",
    0x1F: "Repel",
    0x20: "Rare Candy",
    0x2A: "Bicycle",
    0x3E: "Exp. Share",
}


def species_name(species_id: int) -> str:
    if 0 < species_id < len(SPECIES_NAMES):
        return SPECIES_NAMES[species_id]
    return f"Species {species_id}"


def move_name(move_id: int) -> str:
    return MOVE_NAMES.get(move_id, f"Move {move_id}")


def item_name(item_id: int) -> str:
    return ITEM_NAMES.get(item_id, f"Item {item_id}")


def format_choice(move_id: int) -> str:
    return f"{move_id:03d} {move_name(move_id)}"


def parse_choice(text: str) -> int:
    # Expected format: "NNN Name"
    head = (text or "").strip().split(" ", 1)[0]
    return int(head, 10)


def format_species_choice(species_id: int) -> str:
    return f"{species_id:03d} {species_name(species_id)}"


def format_item_choice(item_id: int) -> str:
    return f"{item_id:03d} {item_name(item_id)}"
